const cron = require("node-cron");
const express = require("express");
const nodemailer = require("nodemailer");

app = express();

let transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 465,
  auth: {
    user: "ninavanes1990@gmail.com", //generated by Mailtrap
    pass: process.env.PASSWORD_GMAIL, //generated by Mailtrap
  },
  debug: true, // show debug output
  logger: true, // log information in console
});

let mailOptions = {
  from: '"Cycle Mate" <cyclemate@example.com>',
  to: "ninavanes1990@hotmail.com",
  subject: "Welcome to Cycle Mate!",
  text: "Hey there, it’s our first message sent with Nodemailer ;) ",
  html: "<b>Hey there! </b><br> This is our first message sent with Nodemailer",
};

transporter.sendMail(mailOptions, (error, info) => {
  if (error) {
    return console.log(error);
  }
  console.log("Message sent: %s", info.messageId);
});

//testing CRON JOB
// cron.schedule("* * * * *", function () {
//   console.log("Running Cron Job");
// });

app.listen(8000);
